[package]
name = "rt_in_one_weekend"
version = "0.1.0"
authors = ["shenchupeng <shenchupeng@corp.netease.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = "0.23.9"
getset = "0.1"
derive-new = "0.5"

